/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Test;
import static org.junit.Assert.*;

public class LibraryTest2 {
    @Test public void testSomeLibraryMethod() {
        Library classUnderTest = new Library();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }
    @Test
	public void testCustomerProfile() {
		Customer u1 = new Customer("Hulk", 9487);
		assertEquals("Hulk", u1.getName());
		assertEquals(9487, u1.getID());
	}

}
